import { EmergencyReport, Alert } from '@/types';

export const MOCK_INCIDENTS: EmergencyReport[] = [
  {
    id: 'inc1',
    userId: 'user1',
    type: 'flood',
    severity: 'critical',
    description: 'Water rising rapidly in my area. Need immediate evacuation.',
    location: { latitude: 37.7749, longitude: -122.4194, accuracy: 10, timestamp: Date.now() - 300000 },
    status: 'in-progress',
    createdAt: new Date(Date.now() - 300000).toISOString(),
    updatedAt: new Date(Date.now() - 100000).toISOString(),
  },
  {
    id: 'inc2',
    userId: 'user2',
    type: 'injury',
    severity: 'medium',
    description: 'Person injured from fallen debris. Conscious and bleeding.',
    location: { latitude: 37.7849, longitude: -122.4094, accuracy: 10, timestamp: Date.now() - 600000 },
    status: 'pending',
    createdAt: new Date(Date.now() - 600000).toISOString(),
    updatedAt: new Date(Date.now() - 600000).toISOString(),
  },
  {
    id: 'inc3',
    userId: 'user3',
    type: 'trapped',
    severity: 'critical',
    description: 'Two people trapped under rubble. Can hear them calling.',
    location: { latitude: 37.7649, longitude: -122.4294, accuracy: 10, timestamp: Date.now() - 900000 },
    status: 'in-progress',
    createdAt: new Date(Date.now() - 900000).toISOString(),
    updatedAt: new Date(Date.now() - 200000).toISOString(),
  },
  {
    id: 'inc4',
    userId: 'user4',
    type: 'food',
    severity: 'low',
    description: 'Need food and water. Stranded at temporary shelter.',
    location: { latitude: 37.7549, longitude: -122.4394, accuracy: 10, timestamp: Date.now() - 1200000 },
    status: 'pending',
    createdAt: new Date(Date.now() - 1200000).toISOString(),
    updatedAt: new Date(Date.now() - 1200000).toISOString(),
  },
];

export const MOCK_ALERTS_DATA: Alert[] = [
  {
    id: 'a1',
    title: 'Flash Flood Warning',
    message: 'Heavy rainfall expected in the next 2 hours. Evacuate low-lying areas immediately.',
    severity: 'critical',
    type: 'evacuation',
    timestamp: Date.now() - 300000,
    read: false,
  },
  {
    id: 'a2',
    title: 'Evacuation Order - Zone A',
    message: 'All residents in Zone A must evacuate immediately. Head to designated shelters.',
    severity: 'high',
    type: 'evacuation',
    timestamp: Date.now() - 600000,
    read: false,
  },
  {
    id: 'a3',
    title: 'Safety Tip: During Floods',
    message: 'Move to higher ground immediately. Do not attempt to cross flooded areas. Call emergency services.',
    severity: 'high',
    type: 'safety-tip',
    timestamp: Date.now() - 900000,
    read: true,
  },
  {
    id: 'a4',
    title: 'Safe Routes Updated',
    message: 'Updated evacuation routes now available in the Map section of the app.',
    severity: 'high',
    type: 'warning',
    timestamp: Date.now() - 1200000,
    read: true,
  },
];
